ECUAPP_SITE = https://github.com/pawelwojtowicz/ecuApp.git
ECUAPP_SITE_METHOD = git
ECUAPP_VERSION = v1.20
ECUAPP_SOURCE = ecuApp-$(ECUAPP_VERSION).tar.gz
ECUAPP_INSTALL_STAGING = YES
ECUAPP_INSTALL_TARGET = YES
ECUAPP_DEPENDENCIES = flite
ECUAPP_CONF_OPTS = -DECUAPP_INSTALL_ROOT=$(TARGET_DIR)

$(eval $(cmake-package))
